add a check for repository name collision; check if an existing project is already versioned; fix a couple of bugs on groovy-plus; spinner added to every gradle operation and remote check

diff --git a/gigawatt b/gigawatt
--- a/gigawatt
+++ b/gigawatt
@@ -11,7 +11,7 @@
 ## @version: 0.9.9b                                       ##
 ## @author: Giuseppe Ricupero                             ##
 ## @e-mail: <giuseppe.ricupero@polito.it>                 ##
-## @date: 16-08-2016 15.33                                ##
+## @date: 18-08-2016 15.56                                ##
 ## @description:                                          ##
 ## upload a freshly created or exising software project   ##
 ## to your favorite git backend at the speed of light!    ##
@@ -27,13 +27,15 @@ fi
 
 # Shell settings and miscellanea {{{
 # ------------------------------
+# bash unofficial strict mode
 set -e # exit if any command has a non-zero exit status (we avoid tests)
 set -u # treat unset variables as an error
 set -o pipefail # if any command in a pipeline fails, that return code will be used as the return code of the whole pipeline
 IFS=$'\n\t'
+# absolute path of the real gigawatt executable
 readonly gwFILE="$(readlink -e "$(type -P "${BASH_SOURCE}" || echo "${BASH_SOURCE}")")"
-readonly gwNAME="${gwFILE##*/}"
-readonly gwDIR="${gwFILE%/*}"
+readonly gwNAME="${gwFILE##*/}" # basename
+readonly gwDIR="${gwFILE%/*}"   # dirname
 # }}}
 
 # import base functions {{{
@@ -47,17 +49,8 @@ declare -a gwDEPS=(getopt curl sed grep ssh ssh-keygen git ping timeout)
 check_deps gwDEPS "$gwNAME"
 # }}}
 
-# general connection test {{{
-# -----------------------
-# yahoo servers reply to ICMP
-if ! reachable 'www.yahoo.com'; then
-	echo >&2 "'${gwNAME}' require an internet connection to work correctly. Aborting."
-	exit 1
-fi
-# }}}
-
-# custom functions {{{
-# ----------------
+# general functions {{{
+# -----------------
 source ${gwDIR}/lib/general
 # }}}
 
@@ -109,7 +102,7 @@ case "$comma" in
 			exit 0
 		fi
 		shift;shift;;
-	set-default)
+	default-profile)
 		if [[ $param == nop ]]; then
 			eecho "Profile name is missing."
 			exit 1
@@ -117,7 +110,7 @@ case "$comma" in
 			eecho "Profile '$param' does not exists."
 			exit 1
 		else
-			git config "${gwNAME}.default-profile" "$param"
+			git config --global "${gwNAME}.default-profile" "$param"
 			profiles_status
 			exit 0
 		fi
@@ -179,7 +172,7 @@ while true; do
 		;;
 		*)
 			slog "Parameters error"
-			exit 1
+			gwhelp; exit 1
 		;;
 	esac
 done
@@ -189,14 +182,17 @@ done
 
 ## 0. variables initializiation {{{
 # -----------------------------
-# assign default
+# Profile
 : "${profiles:="$(profiles)"}"; : "${profiles:=\$s}" # unmatchable
 : "${profile:=$(git config "$gwNAME".default-profile)}"; : "${profile:=off}"
-: "${description:="A '$gwNAME' powered project."}"
-: "${igniter:=$(git config "$profile".default-igniter)}"; : "${igniter:=off}"
-: "${versioned:=on}"
-# Mandatory params check
 [[ ! $profile =~ ^(${profiles})$ ]] && ( slog -hg "No valid profile specified or available as default."; usage; exit 1 )
+# Igniter
+: "${igniter:=$(git config "$profile".default-igniter)}"; : "${igniter:=off}"
+# Version Control
+: "${versioned:=on}"
+# Description
+: "${description:="A '$gwNAME' powered project."}"
+#
 readonly workspace="$(git config "${profile}.workspace")"
 readonly project_dir="/tmp/${gwNAME}/${project}"
 # }}}
@@ -205,15 +201,32 @@ readonly project_dir="/tmp/${gwNAME}/${project}"
 # yahoo servers reply to ICMP
 if [[ $versioned == on ]]; then
 	(
+		git_ssh_user="$(git config "${profile}".ssh-user)"
 		git_host="$(git config "${profile}".host)"
-		if ! reachable "$git_host"; then
-			echo >&2 "The git backend '${git_host}' is not reachable. Aborting..."
+		if ! git_ssh_test "$git_ssh_user" "$git_host"; then
+			eecho "Can't login to the git backend '${git_host}'. Aborting..."
+			exit 1
+		fi
+
+		git_backend="$(git config "$profile".backend)"
+		git_token="$(git config "$profile".token)"
+		git_api="$(git config "$profile".api)"
+		git_user="$(git config "$profile".user)"
+		if git_repository_unavailable \
+			"${git_backend}" \
+			"${git_token}" \
+			"${git_api}" \
+			"${git_user}" \
+			"${project}"
+		then
+			eecho "A repository named '${project}' is already on '${git_backend}'."
+			eecho "See: ${git_host}/${git_user}/${project}"
 			exit 1
 		fi
 	)
 fi
-
 # }}}
+
 ## 2. Remove potential tmp project {{{
 ## -------------------------------
 [[ -d "${project_dir}" ]] && rm -rf "${project_dir}"
@@ -244,8 +257,13 @@ if [[ $use_existing == off ]]; then
 		done
 	fi
 elif [[ ! -d "${workspace}/${project}" ]]; then
-		eecho "The project '${workspace}/${project}' does not exists. Cannot add it."
-		exit 1
+	eecho "The project '${workspace}/${project}' does not exists. Cannot add it."
+	exit 1
+elif (cd "${workspace}/${project}" && git rev-parse --git-dir &>/dev/null); then
+	eecho "The project '${workspace}/${project}' is already versioned with git."
+	eecho "Remote list: "
+	(cd "${workspace}/${project}" && git remote -v)
+	exit 1
 fi
 # }}}
 
diff --git a/igniters/groovy-plus b/igniters/groovy-plus
--- a/igniters/groovy-plus
+++ b/igniters/groovy-plus
@@ -50,8 +50,10 @@ asks_jdk_parameters() {
 	# application
 	slog -hg 'Do you want to create an application instead of a library? (no)'
 	select REPLY in yes no; do
-		application=$REPLY
-		break
+		case $REPLY in
+			yes) application=on; break;;
+			no) application=off; break;;
+		esac
 	done
 
 	# package
@@ -72,22 +74,29 @@ asks_jdk_parameters() {
 	# fatjar
 	slog -hg 'Do you want to create a fatjar? (no)'
 	select REPLY in yes no; do
-		fatjar=$REPLY
-		break
+		case $REPLY in
+			yes) fatjar=on; break;;
+			no) fatjar=off; break;;
+		esac
 	done
 	# nexus
 	slog -hg 'Do you want to add support for a nexus server? (no)'
 	select REPLY in yes no; do
 		case $REPLY in
-			yes)
-				nexus=on
-				break;;
-			no)
-				nexus=off
-				break;;
+			yes) nexus=on; break;;
+			no) nexus=off; break;;
 		esac
 	done
 }
+
+# general connection test {{{
+# -----------------------
+# yahoo servers reply to ICMP
+if ! reachable 'www.yahoo.com'; then
+	echo >&2 "'${igNAME}' require an internet connection to work correctly. Aborting."
+	exit 1
+fi
+# }}}
 
 ## asks to customize parameters {{{
 slog -hg 'Do you want to customize parameters? (no)'
@@ -144,8 +153,8 @@ hashmap_to_file() { # {{{
 
 add_gradle_properties() { # {{{
 	local -A nexus_properties=( [nexusUrl]="$1"
-	                            [nexusUsername]="$2"
-	                            [nexusPassword]="$3" )
+	                           [nexusUsername]="$2"
+	                           [nexusPassword]="$3" )
 
 	local outfile="gradle.properties"
 
@@ -265,10 +274,10 @@ add_build_gradle() { # {{{
 	|	description           "${ldescription}"
 	|	wrapper.gradleVersion "\$gradleVersion"
 	$(
-		[[ $lapp == on ]] && { 
+		[[ $lapp == on ]] && {
 			echo "	// executed if no other tasks are specified"
 			echo "	defaultTasks          'clean', 'run'"
-			echo "	// application entry point" 
+			echo "	// application entry point"
 			echo "	mainClassName = 'Launcher'"
 		}; echo '}'
 	)
@@ -501,7 +510,7 @@ EOF
 # }}}
 
 ## build skeleton of the project {{{
-gradle init --type groovy-library &>/dev/null
+silent_gradle init --type groovy-library
 # }}}
 
 ## 2. Remove ${gradle_conf}, ${default_class}, ${default_test} {{{
@@ -641,8 +650,9 @@ add_build_gradle \
 	"${application}" \
 	"${fatjar}" \
 	"${nexus}"
+
 # unit test 7.1
-if ! gradle tasks &>/dev/null; then
+if ! silent_gradle tasks; then
 	slog "File '${gradle_conf}' not created correctly: exiting..."
 	exit 1
 fi
@@ -655,7 +665,7 @@ testpath="${test_dir}/${package_path}"
 add_library "${mainpath}" "${main_class}" "${package_name}"
 add_library_specification "${testpath}" "${main_class}" "${package_name}"
 # unit test 7.2
-if ! gradle test &>/dev/null; then
+if ! silent_gradle test; then
 	slog "Files '$main_class', '${main_class}Spec' not created correctly: exiting..."
 	exit 1
 fi
@@ -718,7 +728,7 @@ add_log4j2_conf "${log4j_conf}"
 # }}}
 
 ## eclipse project files: .classpath, .project, .settings {{{
-gradle eclipse &>/dev/null
+silent_gradle eclipse
 # unit test 10
 for ep_file in classpath project settings; do
 	if [[ ! -e .${ep_file} ]]; then
